title: "Distillation Column Design & Analysis"
description: "An example for the design of a ethanol-water distillation column using a McCabe-Thiele Diagram and other standard chemical engineering formulae. Using a similarly sized distillation column data sourced from Kaggle, a model will be trained for predicting final ethanol distillate concentration and then tested on the designed column."
theme: just-the-docs
navigation:
  - title: "Introduction"
    url: "/"
  - title: "Column Design Information"
    url: "/"
  - title: "Distillation Column Results"
    url: "/distillation"
    children:
      - title: "Column Data Sorting & Initialising"
        url: "/result/sorting"
      - title: "McCabe-Thiele Construction"
        url: "/distillation/MCC-construction"
      - title: "Test Data Operating & Analysis"
        url: "/distillation/Analysis"
      - title: "Prediction Outcome, Explanation & Possible Improvements"
        url: "/distillation/Conclusion"
plugins:
  - jekyll-feed
permalink: /:title/  
