title: "Distillation Column Design & Analysis"
description: "An example for the design of a ethanol-water distillation column using a McCabe-Thiele Diagram and other standard chemical engineering formulae. Using a similarly sized distillation column data sourced from Kaggle, a model will be trained for predicting final ethanol distillate concentration and then tested on the designed column."
theme: just-the-docs
navigation:
  - title: "Home"
    url: "/"
  - title: "Distillation Column"
    url: "/distillation"
    children:
      - title: "Introduction"
        url: "/distillation/intro"
      - title: "Design Considerations"
        url: "/distillation/design"
      - title: "Data Analysis"
        url: "/distillation/analysis"

